import 'package:jetleaf_lang/lang.dart';

import '../../annotations/configuration_properties.dart';
import 'object_binder.dart';

/// Describes a single property (field or constructor parameter) within a class.
class BindableProperty {
  final String name;
  final Type type;
  final Object? defaultValue;
  final bool isNested;
  final bool isRequired; // For constructor parameters

  BindableProperty({
    required this.name,
    required this.type,
    this.defaultValue,
    this.isNested = false,
    this.isRequired = false,
  });
}

/// Describes a constructor to be used for binding.
class BindableConstructor {
  final List<BindableProperty> parameters;

  BindableConstructor({required this.parameters});
}

/// A schema that explicitly defines how a class should be bound.
///
/// This replaces runtime reflection (`dart:mirrors`) by providing all
/// necessary metadata at compile time. In a real application, instances
/// of this class would typically be generated by a build tool.
@Generic(ClassBindingSchema)
class ClassBindingSchema<T> {
  final Type type;
  final ConfigurationProperties configAnnotation;
  final BindableConstructor? constructor; // If constructor binding is used
  final Map<String, BindableProperty> properties; // For field-based binding

  /// A factory function to create an instance of the class.
  /// This is used by the Binder to instantiate the object.
  final ObjectBinder<T> objectBinder;

  ClassBindingSchema({
    required this.type,
    required this.configAnnotation,
    this.constructor,
    required this.properties,
    required this.objectBinder,
  });
}