import 'package:jetleaf_lang/lang.dart';

/// An interface for creating and populating instances of a specific type [T].
///
/// In a real application, implementations of this interface would typically
/// be generated by a build tool (e.g., `build_runner`) based on annotations
/// on the configuration classes.
@Generic(ObjectBinder)
abstract class ObjectBinder<T> {
  /// Creates a new instance of [T] using the provided [values].
  ///
  /// [values] is a map where keys are property names (e.g., 'port', 'host')
  /// and values are the bound property values.
  T createInstance(Map<String, dynamic> values);

  /// Sets a specific [fieldName] on the given [instance] with the [value].
  ///
  /// This method is primarily for mutable fields if constructor binding is not used
  /// or for properties that are set after initial construction.
  void setField(T instance, String fieldName, dynamic value);
}